name: nuc_polymetis_server
channels:
  - defaults
  - pytorch
  - fair-robotics
  - aihabitat
  - conda-forge
dependencies:
  - python=3.8
  - polymetis
  - pip
  - protobuf
  - zarr
  - pip:
      - pyzmq
      - scipy
      - h5py
      - Flask
      - blosc==1.11.1
      - ikpy
      - shapely
      - rospkg
      - IPython
      - pyrealsense2
      - gunicorn
      - gevent
      - pillow=10.1.0
      - opencv-contrib-python
