n_frames: 3000
realsense:
  n_frames: ${n_frames}
  width: 1920
  height: 1080
  fps: 6

writer:
  episodes_path: "/home/rvl_root/Desktop/ACMERealWorld/outputs/calibration"
  target:
    target_type: 'aprilgrid'
    tagCols: 6
    tagRows: 6
    tagSize: 0.1      #size of one chessboard square [m]
    tagSpacing: 0.2      #size of one chessboard square [m]
  max_episode_len: ${n_frames}
  n_cameras: 5
  captures:
    frame_width: ${realsense.width}
    frame_height: ${realsense.height}
    max_episode_len: ${writer.max_episode_len}

hydra:
  output_subdir: null
  run:
    dir: .