max_episode_timesteps: 150

nuc:
  ip: "192.168.1.106"

realsense:
  width: 1280
  height: 720
  fps: 6

writer:
  episodes_path: "/home/rvl_root/Desktop/ACMERealWorld/episodes"
  max_episode_len: ${max_episode_timesteps}
  n_cameras: 4
  captures:

    frame_width: ${realsense.width}
    frame_height: ${realsense.height}
    max_episode_len: ${writer.max_episode_len}
    fps: ${realsense.fps}

gello:
  base_index: 8
  baud_rate: 115200
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U2GH-if00-port0"
  joint_signs:
    - 1
    - -1
    - 1
    - 1
    - 1
    - -1
    - 1
  start_joints:
    - 0
    - 0
    - 0
    - -1.57
    - 0
    - 1.57
    - 0

hydra:
  output_subdir: null
  run:
    dir: .