max_episode_timesteps: 250

nuc:
  ip: "192.168.1.106"
  franka_ip: "192.168.1.107"
  server:
    ip: ${nuc.ip}
    port: 22
    user: ${env:NUC_USER}
    pwd: ${env:NUC_PWD}
    conda: "/home/james/anaconda3"

realsense:
  n_frames: ${max_episode_timesteps}
  width: 1280
  height: 720
  fps: 15

writer:
  episodes_path: "/home/rvl_root/Desktop/ACMERealWorld/output/episodes"
  max_episode_len: ${max_episode_timesteps}
  n_cameras: 4
  captures:

    frame_width: ${realsense.width}
    frame_height: ${realsense.height}
    max_episode_len: ${writer.max_episode_len}
    fps: ${realsense.fps}

gello:
  base_index: 8
  baud_rate: 115200
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U2GH-if00-port0"
  joint_signs:
    - 1
    - -1
    - 1
    - 1
    - 1
    - 1q
    - 1
  start_joints:
    - 0
    - 0
    - 0
    - -1.57
    - 0
    - 1.57
    - 0

hydra:
  output_subdir: null
  run:
    dir: .